name: docker
services:
  admin-backend:
    environment:
      ELASTIC_SEARCH_URL: http://localhost:9200
      GUP_INDEX_MANAGER_API_KEY: megasecretimpossibletoguesskey
      GUP_INDEX_MANAGER_URL: http://localhost:4010
    image: docker.ub.gu.se/gup-admin-backend:release-2023.06.015-arm64
    networks:
      default: null
    ports:
    - mode: ingress
      target: 4000
      published: "4000"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /Users/johanlarsson/Dev/gup-super/data/_source
      target: /release/data/_source
      bind:
        create_host_path: true
    - type: bind
      source: /Users/johanlarsson/Dev/gup-super/data/scopus-normalised
      target: /release/data/scopus-normalised
      bind:
        create_host_path: true
  admin-db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: gup_admin_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:12
    networks:
      default: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 5432
      published: "5433"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /Users/johanlarsson/Dev/gup-super/docker/docker-entrypoint-initdb.d
      target: /docker-entrypoint-initdb.d
      bind:
        create_host_path: true
  admin-frontend:
    image: docker.ub.gu.se/gup-admin-admin-frontend:release-2023.06.015-arm64
    networks:
      default: null
    ports:
    - mode: ingress
      target: 4000
      published: "3000"
      protocol: tcp
  elasticsearch:
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node
      xpack.security.enabled: "false"
    image: docker.ub.gu.se/gup-admin-elasticsearch:release-2023.06.015-arm64
    networks:
      default: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 9200
      published: "9200"
      protocol: tcp
    - mode: ingress
      host_ip: 127.0.0.1
      target: 9300
      published: "9300"
      protocol: tcp
    restart: always
  index-manager-backend:
    environment:
      ELASTIC_SEARCH_URL: http://localhost:9200
      GUP_BASE_URL: https://gup-lab.ub.gu.se
    image: docker.ub.gu.se/gup-admin-index-manager-backend:release-2023.06.015-arm64
    networks:
      default: null
    ports:
    - mode: ingress
      target: 4000
      published: "4010"
      protocol: tcp
    restart: always
  index-manager-db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: gup_index_manager_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:12
    networks:
      default: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 5432
      published: "5443"
      protocol: tcp
    restart: always
    volumes:
    - type: bind
      source: /Users/johanlarsson/Dev/gup-super/db/initialize
      target: /docker-entrypoint-initdb.d
      bind:
        create_host_path: true
networks:
  default:
    name: docker_default