version: '3.7'

services:
  db-index-manager:
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data/pgdata
  frontend-nuxt:
    image: docker.ub.gu.se/gup-admin-frontend-nuxt:${GIT_REVISION}
    environment:
      NUXT_API_BASE_URL: "http://backend:4000/"
      NUXT_API_ALERT_URL: "${ALERT_URL}"
    ports:
      - ${FRONTEND_HOST_PORT}:3000
