version: "3.7"
services:
  admin-frontend:
    command: ["bash", "-c", "yarn install && yarn dev"]
    environment:
      NUXT_PUBLIC_API_GUP_BASE_URL: "http://localhost:8181" # This should be a link directly to gup frontend. We need to be able to link directly to a post in gup from admin-frontend
    volumes:
      - ../frontend:/app # GUP_ADMIN_REPO is not set anywhere in the project
  admin-backend:
    environment:
      MIX_ENV: dev
      GUP_BASE_URL: "http://localhost:8181"
    volumes:
      - ../backend:/app # GUP_ADMIN_REPO is not set anywhere in the project
      # Temporary fix until real index is in place
      - ../data/_source:/release/data/_source
      - ../data/scopus-normalised:/release/data/scopus-normalised
    command:
      [
        "sh",
        "-c",
        "mix deps.get && mix deps.compile && mix phx.digest && /usr/local/bin/wait-for-it.sh admin-db:5432 elasticsearch:9200 -t 0 -- mix phx.server",
      ]
  index-manager-backend:
    environment:
      - MIX_ENV=dev

    volumes:
      - ../index_manager:/app # GUP_ADMIN_REPO is not set anywhere in the project
    command:
      [
        "sh",
        "-c",
        "mix deps.get && mix deps.compile && mix phx.digest && /usr/local/bin/wait-for-it.sh index-manager-db:5432 elasticsearch:9200 -t 0 -- mix phx.server",
      ]
  index-manager-db:
    ports:
      - "127.0.0.1:5443:5432"
  elasticsearch:
    ports:
      - "127.0.0.1:9200:9200"

