version: '3.7'
services:
  index-manager-db:
    ports:
      - "127.0.0.1:5433:5432" #???
  admin-frontend:
    environment:
      NUXT_AUTH_BASE_URL: "${FRONTEND_PUBLIC_URL}"
      NUXT_AUTH_ORIGIN: "${FRONTEND_PUBLIC_URL}"
      NUXT_PUBLIC_API_GUP_BASE_URL: "${GUP_FRONTEND_PUBLIC_URL}"
    restart: always
  admin-backend:
    environment:
      GUP_BASE_URL: "${GUP_FRONTEND_PUBLIC_URL}"
      GUP_SERVER_BASE_URL: "${GUP_BACKEND_PUBLIC_URL}"
