version: "3.7"

services:
  gup-frontend:
    image: docker.ub.gu.se/gup-frontend:${GIT_REVISION_GUP}
    restart: always
    ports:
      - "3010:8080"
    environment:
      - EMBER_ENVIRONMENT=development
      - GUP_SERVICE_PORT=${GUP_BACKEND_PORT}
      - GUP_MAX_NUMBER_OF_POSTS_RIS=${GUP_MAX_NUMBER_OF_POSTS_RIS}
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as debugging, etc
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container
    tty: true
  gup-backend:
    image: docker.ub.gu.se/gup-backend:${GIT_REVISION_GUP}
    depends_on:
      - gup-db
    environment:
      - RAILS_ENV=${GUP_ENVIRONMENT}
      - RAILS_PORT=${GUP_RAILS_PORT}
      - GUP_AUTH_OVERRIDE=${GUP_AUTH_OVERRIDE}
      - GUP_SECRET_KEY_BASE=${GUP_SECRET_KEY_BASE}
      - GUP_DB_HOST=${GUP_DB_HOST}
      - GUP_DB_PORT=${GUP_DB_PORT}
      - GUP_DB=${GUP_DB}
      - GUP_DB_USER=${GUP_DB_USER}
      - GUP_DB_PASSWORD=${GUP_DB_PASSWORD}
      - GUP_SOLR_HOST=solr
      - GUP_SOLR_PORT=8983
      - GUP_TEST_USER_API_KEY=${GUP_TEST_USER_API_KEY}
      - GUP_SCOPUS_API_KEY=${GUP_SCOPUS_API_KEY}
      - GUP_GUPEA_OAI_BASE_URL=${GUP_GUPEA_OAI_BASE_URL}
      - GUP_GUPEA_OAI_METADATA_PREFIX=${GUP_GUPEA_OAI_METADATA_PREFIX}
      - GUP_GUPEA_OAI_IDENTIFIER_PREFIX=${GUP_GUPEA_OAI_IDENTIFIER_PREFIX}
      - GUP_SMTP_SERVER=${GUP_SMTP_SERVER}
      - GUP_SMTP_PORT=${GUP_SMTP_PORT}
      - GUP_SMTP_AUTH=${GUP_SMTP_AUTH}
      - GUP_SMTP_USERNAME=${GUP_SMTP_USERNAME}
      - GUP_SMTP_PASSWORD=${GUP_SMTP_PASSWORD}
      - GUP_SMTP_ENABLE_STARTTLS_AUTO=${GUP_SMTP_ENABLE_STARTTLS_AUTO}
      - GUP_MAIL_FROM=${GUP_MAIL_FROM}
      - GUP_MAIL_TO=${GUP_MAIL_TO}
      - GUP_REPOSITORY_NAME=${GUP_REPOSITORY_NAME}
      - GUP_OAI_REPOSITORY_NAME=${GUP_OAI_REPOSITORY_NAME}
      - GUP_OAI_RECORD_PREFIX=${GUP_OAI_RECORD_PREFIX}
      - GUP_MQ_BASE_URL=${GUP_MQ_BASE_URL}
      - GUP_MQ_API_KEY=${GUP_MQ_API_KEY}
      - GUP_PUBLIC_BASE_URL=${GUP_PUBLIC_BASE_URL}
      - GUP_HOSTNAME=${BACKEND_OAI_HOSTNAME}
      - LOG_FILE_PATH=${LOG_FILE_PATH}
      - GUP_MAX_NUMBER_OF_POSTS_RIS=${GUP_MAX_NUMBER_OF_POSTS_RIS}
      - GUP_ADMIN_BASE_URL=${GUP_ADMIN_BASE_URL}
      - GUP_ADMIN_API_KEY=${GUP_ADMIN_API_KEY}
      - GUP_ADMIN_PUBLICATION_ENABLE=${GUP_ADMIN_PUBLICATION_ENABLE}
      - GUP_ADMIN_PERSON_ENABLE=${GUP_ADMIN_PERSON_ENABLE}
    ports:
      - ${GUP_BACKEND_PORT}:${GUP_RAILS_PORT}
    volumes:
      - ${GUP_BACKEND_UPLOADS_VOLUME_SOURCE}:/opt/gup-uploads
      - ${GUP_BACKEND_SITEMAPS_DIR}:/apps/gup/sitemaps
  gup-db:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=${GUP_DB}
      - POSTGRES_USER=${GUP_DB_USER}
      - POSTGRES_PASSWORD=${GUP_DB_PASSWORD}
    volumes:
      - ./db-data-gup-seed:/docker-entrypoint-initdb.d
      - ${GUP_DB_VOLUME_SOURCE}:/var/lib/postgresql/data
  solr:
    image: docker.ub.gu.se/gup-solr:${GIT_REVISION_GUP}
    environment:
      - GUP_SOLR_DATA_IMPORT_DB_URL=jdbc:postgresql://db:5432/${GUP_DB}
      - GUP_SOLR_DATA_IMPORT_DB_USER=${GUP_DB_USER}
      - GUP_SOLR_DATA_IMPORT_DB_PASSWORD=${GUP_DB_PASSWORD}
    depends_on:
      - gup-db
    ports:
      - ${GUP_SOLR_PORT}:8983
    volumes:
      - ${GUP_SOLR_GURESEARCH_VOLUME_SOURCE}:/opt/solr/server/solr/mycores/gup-guresearch/data
      - ${GUP_SOLR_JOURNALS_VOLUME_SOURCE}:/opt/solr/server/solr/mycores/gup-journals/data
      - ${GUP_SOLR_PEOPLE_VOLUME_SOURCE}:/opt/solr/server/solr/mycores/gup-people/data
      - ${GUP_SOLR_PUBLICATIONS_VOLUME_SOURCE}:/opt/solr/server/solr/mycores/gup-publications/data
