version: '3.7'
services:
  index-manager-db:
    ports:
      - "127.0.0.1:5433:5432" #???
  admin-frontend:
    environment:
      NUXT_AUTH_BASE_URL: "${FRONTEND_PUBLIC_URL}"
      NUXT_PUBLIC_API_GUP_BASE_URL: "${GUP_FRONTEND_PUBLIC_URL}"
      #NUXT_AUTH_ORIGIN: "${AUTH_ORIGIN}" does not seems to be used
    restart: always
  admin-backend:
    environment:
      GUP_BASE_URL: "${GUP_FRONTEND_PUBLIC_URL}"
      GUP_SERVER_BASE_URL: "${GUP_BACKEND_PUBLIC_URL}"
    volumes:
      # Temporary fix until real index is in place
      - ../data/_source:/app/data/_source
      - ../data/scopus-normalised:/app/data/scopus-normalised
