version: '3.7'
services:
  admin-frontend:
    command: ["bash", "-c", "yarn install && yarn dev"]
    environment:
      NUXT_PUBLIC_API_GUP_BASE_URL: "http://localhost:$ADMIN_BACKEND_HOST_PORT"
    volumes:
      - ${GUP_ADMIN_REPO}/frontend:/app
    networks:
      - gup-admin
  admin-backend:
    environment:
      MIX_ENV: dev
      GUP_BASE_URL: "localhost:8181"
    volumes:
      - ${GUP_ADMIN_REPO}/backend:/app
    command: ["sh", "-c", "mix deps.get && mix deps.compile && mix phx.digest && /usr/local/bin/wait-for-it.sh admin-db:5432 elasticsearch:9200 -t 0 -- mix phx.server"]
    networks:
      - gup
      - gup-admin
  index-manager-backend:
    environment:
      - MIX_ENV=dev
    command: ["sh", "-c", "mix deps.get && mix deps.compile && mix phx.digest && /usr/local/bin/wait-for-it.sh index-manager-db:5432 elasticsearch:9200 -t 0 -- mix phx.server"]
    volumes:
      - ${GUP_ADMIN_REPO}/index_manager:/app
      - ./department-files:/app/data/departments #???
    networks:
      - gup-admin
  admin-db:
    networks:
      - gup-admin
  index-manager-db:
    networks:
      - gup-admin
  elasticsearch:
    networks:
      - gup-admin
networks:
  gup:
    name: gup
    external: true
  gup-admin:
