version: '3.7'

services:
#  db: 
#    volumes:
#- ${DB_DATA_PATH}:/var/lib/postgresql/data/pgdata
  frontend-nuxt:
    image: docker.ub.gu.se/gup-admin-frontend-nuxt:${GIT_REVISION}
    environment:
      NUXT_API_BASE_URL: "http://backend:8001"
      NUXT_API_ALERT_URL: "${ALERT_URL}"
    ports:
      - ${FRONTEND_HOST_PORT}:3000