version: "3.7"

services:
  admin-frontend:
    image: docker.ub.gu.se/gup-admin-frontend:${GIT_REVISION}${PLATFORM}
    ports:
      - "${ADMIN_FRONTEND_HOST_PORT}:3000"
    environment:
      NUXT_API_BASE_URL: "http://admin-backend:4000/"
      NUXT_PUBLIC_API_GUP_BASE_URL_EDIT: "${NUXT_API_GUP_BASE_URL_EDIT}"
      NUXT_PUBLIC_API_GUP_BASE_URL_SHOW: "${NUXT_API_GUP_BASE_URL_SHOW}"
      NUXT_PUBLIC_ALLOW_AUTHOR_EDIT: "${NUXT_ALLOW_AUTHOR_EDIT}"
      NUXT_PUBLIC_API_GUP_BASE_URL_EDIT_AUTHOR: "${NUXT_API_GUP_BASE_URL_EDIT_AUTHOR}"
    restart: always
  admin-backend:
    image: docker.ub.gu.se/gup-admin-backend:${GIT_REVISION}${PLATFORM}
    ports:
      - "${ADMIN_BACKEND_HOST_PORT}:4000"
    environment:
      ELASTIC_SEARCH_URL: "${ELASTIC_SEARCH_URL}"
      GUP_INDEX_MANAGER_URL: "${GUP_INDEX_MANAGER_URL}"
      GUP_INDEX_MANAGER_API_KEY: "${GUP_INDEX_MANAGER_API_KEY}"
      GUP_SERVER_BASE_URL: "${GUP_SERVER_BASE_URL}"
      GUP_BASE_URL: "${GUP_BASE_URL}"
      GUP_API_KEY: "${GUP_API_KEY}"
    restart: always
    volumes:
      # Temporary fix until real index is in place
      - ../data/_source:/release/data/_source
      - ../data/scopus-normalised:/release/data/scopus-normalised
  index-manager-backend:
    image: docker.ub.gu.se/gup-admin-index-manager-backend:${GIT_REVISION}${PLATFORM}
    ports:
      - "${BACKEND_INDEX_MANAGER_HOST_PORT}:4000"
    environment:
      ELASTIC_SEARCH_URL: "${ELASTIC_SEARCH_URL}"
      GUP_BASE_URL: "${GUP_BASE_URL}"
      GUP_INDEX_MANAGER_API_KEY: "${GUP_INDEX_MANAGER_API_KEY}"
    restart: always
    volumes:
      - "./department-files:/release/data/departments"
  admin-db:
    image: postgres:12
    environment:
      POSTGRES_USER: "${ADMIN_DB_USER}"
      POSTGRES_PASSWORD: "${ADMIN_DB_PASSWORD}"
      POSTGRES_DB: "${ADMIN_DB_NAME}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "${DB_INIT_PATH}:/docker-entrypoint-initdb.d"
    ports:
      - "127.0.0.1:5433:5432"
    restart: always
  index-manager-db:
    image: postgres:12
    environment:
      POSTGRES_USER: "${ADMIN_DB_USER}"
      POSTGRES_PASSWORD: "${ADMIN_DB_USER}"
      POSTGRES_DB: "${INDEX_MANAGER_DB_NAME}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "${DB_INDEX_MANAGER_INIT_PATH}:/docker-entrypoint-initdb.d"
    ports:
      - "127.0.0.1:5443:5432"
    restart: always
  elasticsearch:
    image: docker.ub.gu.se/gup-admin-elasticsearch:${GIT_REVISION}${PLATFORM}
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    restart: always
  gup-imports:
    image: docker.ub.gu.se/gup-imports:${GUP_IMPORTS_IMAGE_VERSION}
    restart: always
    environment:
      - GUP_ADMIN_BASE_URL=${GUP_INDEX_MANAGER_URL}
      - GUP_ADMIN_API_KEY=${GUP_INDEX_MANAGER_API_KEY}
    tty: true
    volumes:
      - ${HOST_SCOPUS_NORMALISED_JSON_FILES_DIR}:/data/files/scopus-normalised
      - ${HOST_SCRIPT_FILES_DIR}:/data/scripts
