version: '3.7'

services:
  index-manager-db:
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data/pgdata
  admin-frontend:
    image: docker.ub.gu.se/gup-admin-admin-frontend:${GIT_REVISION}${PLATFORM}
    environment:
      NUXT_API_BASE_URL: "http://backend:4000/"
      NUXT_API_ALERT_URL: "${ALERT_URL}"
    restart: always
    ports:
      - ${ADMIN_FRONTEND_HOST_PORT}:3000
