#!/bin/bash
mkdir -p db-postgres-initdb.d
mkdir -p index-manager-db-postgres-initdb.d
mkdir -p admin-db-data
mkdir -p elasticsearch-data
mkdir -p index-manager-db-data
mkdir -p scopus-files
mkdir -p scopus-scripts
mkdir -p kibana-data
mkdir -p _source
mkdir -p scopus-normalised
