---
GU_CLIENT_SECRET: '{{ vault_gub_oauth2_client_secret }}'
NUXT_GU_CLIENT_SECRET: '{{ vault_gub_oauth2_client_secret }}'
GITHUB_CLIENT_SECRET: '{{ vault_github_oauth2_client_secret }}'
NUXT_GITHUB_CLIENT_SECRET: '{{ vault_github_oauth2_client_secret }}'

GUP_API_KEY: '{{ vault_gup_api_key }}'
INDEX_MANAGER_API_KEY: '{{ vault_index_manager_api_key }}'
GUP_ADMIN_API_KEY: '{{ vault_index_manager_api_key }}'
SECRET_KEY_BASE: '{{ vault_secret_key_base }}'
NUXT_SECRET_KEY_BASE: '{{ vault_secret_key_base }}'
