// Generated by nitro
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/alert': {
      'default': Awaited<ReturnType<typeof import('../../server/api/alert').default>>
    }
    '/api/post_gup_create/:id': {
      'default': Awaited<ReturnType<typeof import('../../server/api/post_gup_create/[id]').default>>
    }
    '/api/post_gup/:id': {
      'default': Awaited<ReturnType<typeof import('../../server/api/post_gup/[id]').default>>
    }
    '/api/post_imported/:id': {
      'delete': Awaited<ReturnType<typeof import('../../server/api/post_imported/[id].delete').default>>
      'default': Awaited<ReturnType<typeof import('../../server/api/post_imported/[id]').default>>
    }
    '/api/posts_gup_by_id': {
      'default': Awaited<ReturnType<typeof import('../../server/api/posts_gup_by_id').default>>
    }
    '/api/posts_gup_by_title': {
      'default': Awaited<ReturnType<typeof import('../../server/api/posts_gup_by_title').default>>
    }
    '/api/posts_imported': {
      'default': Awaited<ReturnType<typeof import('../../server/api/posts_imported').default>>
    }
    '/api/pubtypes': {
      'default': Awaited<ReturnType<typeof import('../../server/api/pubtypes').default>>
    }
    '/__nuxt_error': {
      'default': Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>
    }
  }
}
export {}