---
- name: Export index manager database
  hosts: all
  roles:
  - role: ub-ansible-export-db
    vars:
      db_service: index-manager-db
      database_variant: postgres
      db_dump_filename: index-manager-database.sql
